version: "3"

volumes:
  hadoop-config:

services:
  elastic:
    image: elasticsearch
    command: elasticsearch -Enode.name="iot"
    ports:
      - "9201:9200"
#    sysctls:
#      - vm.max_map_count=262144
#sysctl -w vm.max_map_count=262144

  hadoop-master:
    image: p4km9y/hadoop-master
    hostname: hadoop-master
    container_name: hadoop-master
    depends_on:
      - elastic
    volumes:
      - hadoop-config:/var/lib/hadoop/config
  hadoop-slave-1:
    image: p4km9y/hadoop-slave
    container_name: hadoop-slave-1
    depends_on:
      - hadoop-master
  hadoop-slave-2:
    image: p4km9y/hadoop-slave
    container_name: hadoop-slave-2
    depends_on:
      - hadoop-master

  flink:
    image: p4km9y/flink:1.3
    depends_on:
      - hadoop-master
    volumes:
      - hadoop-config:/opt/hadoop-config:ro
    environment:
      - "affinity:container==hadoop-master"
#    entrypoint:
#      - /usr/bin/tail
#      - -f
#      - /var/log/lastlog

  zookeeper-leader:
    container_name: zkprl
    hostname: zkprl
    image: p4km9y/zookeeper
  zookeeper-scalable-follower:
    image: p4km9y/zookeeper
    depends_on:
      - zookeeper-leader
    environment:
      - ZK_LEADER=zkprl
      - ZK_SLEEP=4
    entrypoint:
      - /wait-for-it.sh
      - -t
      - "100"
      - -s
      - zkprl:2181
      - --
      - /opt/zookeeper/bin/zk-init.sh
  zookeeper-static-follower:
    container_name: zkprf
    hostname: zkprf
    image: p4km9y/zookeeper
    depends_on:
      - zookeeper-leader
    environment:
      - ZK_LEADER=zkprl
      - ZK_SLEEP=8
    entrypoint:
      - /wait-for-it.sh
      - -t
      - "100"
      - -s
      - zkprl:2181
      - --
      - /opt/zookeeper/bin/zk-init.sh

  kafka-member-1:
    container_name: kfkm1
    hostname: kfkm1
    image: p4km9y/kafka
    depends_on:
      - zookeeper-leader
    entrypoint:
      - /wait-for-it.sh
      - -t
      - "100"
      - -s
      - zkprl:2181
      - --
      - /opt/kafka/bin/kafka-server-start.sh
      - /opt/kafka/config/server.properties
      - --override
      - zookeeper.connect=zkprl:2181,zkprf:2181
      - --override
      - broker.id=1
  kafka-member-2:
    container_name: kfkm2
    hostname: kfkm2
    image: p4km9y/kafka
    depends_on:
      - zookeeper-leader
    entrypoint:
      - /wait-for-it.sh
      - -t
      - "100"
      - -s
      - zkprl:2181
      - --
      - /opt/kafka/bin/kafka-server-start.sh
      - /opt/kafka/config/server.properties
      - --override
      - zookeeper.connect=zkprl:2181,zkprf:2181
      - --override
      - broker.id=2
  kafka-member-3:
    container_name: kfkm3
    hostname: kfkm3
    image: p4km9y/kafka
    depends_on:
      - zookeeper-leader
    entrypoint:
      - /wait-for-it.sh
      - -t
      - "100"
      - -s
      - zkprl:2181
      - --
      - /opt/kafka/bin/kafka-server-start.sh
      - /opt/kafka/config/server.properties
      - --override
      - zookeeper.connect=zkprl:2181,zkprf:2181
      - --override
      - broker.id=3

  mosquitto:
    image: p4km9y/mosquitto
    hostname: mosquitto
    ports:
      - "1883:1883"

  bridge:
    image: p4km9y/karaf
    hostname: bridge
    depends_on:
      - kafka-member-1
      - kafka-member-2
      - kafka-member-3
      - mosquitto
      - meshliumdb

  kibana:
    image: kibana
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
    depends_on:
      - elastic

  meshliumdb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
    ports:
      - "3307:3306"

networks:
  default:
    external:
      name: iot.net
